import minecraft_launcher_lib
import subprocess
import sys
import time

lv = "forge-1.20.1-47.1.0"
md = "."
options = {
    "username": "mikitest",
    "uuid": "-",
    "token": "-"
}

minecraft_command = minecraft_launcher_lib.command.get_minecraft_command(lv, md, options)
minecraft_command.insert(3, '-Dminecraft.launcher.brand=mikiho-skurveny-launcher')
minecraft_command[0] = 'jvm/java-runtime-gamma/bin/javaw.exe'

print('Mikiho launcher > ')
print('')
options['username'] = input("Tvoj nick: ")
print('')
print('Client sa spusta..')

str = ("jvm/java-runtime-gam"
   "ma/bin/javaw.exe -XX"
   ":HeapDumpPath=Mojang"
   "TricksIntelDriversFo"
   "rPerformance_javaw.e"
   "xe_minecraft.exe.hea"
   "pdump -Djava.library"
   ".path=.\\versions\\f"
   "orge-1.20.1-47.1.0\\"
   "natives -Dminecraft."
   "launcher.brand=mikih"
   "o-skurveny-launcher "
   "-Djna.tmpdir=.\\vers"
   "ions\\forge-1.20.1-4"
   "7.1.0\\natives -Dorg"
   ".lwjgl.system.Shared"
   "LibraryExtractPath=."
   "\\versions\\forge-1."
   "20.1-47.1.0\\natives"
   " -Dio.netty.native.w"
   "orkdir=.\\versions\\"
   "forge-1.20.1-47.1.0"
   "\\natives -Dminecraf"
   "t.launcher.brand=min"
   "ecraft-launcher-lib "
   "-Dminecraft.launcher"
   ".version=6.1 -cp .\\"
   "libraries\\cpw\\mods"
   "\\securejarhandler\\"
   "2.1.10\\securejarhan"
   "dler-2.1.10.jar;.\\l"
   "ibraries\\org\\ow2\\"
   "asm\\asm\\9.5\\asm-9"
   ".5.jar;.\\libraries"
   "\\org\\ow2\\asm\\asm"
   "-commons\\9.5\\asm-c"
   "ommons-9.5.jar;.\\li"
   "braries\\org\\ow2\\a"
   "sm\\asm-tree\\9.5\\a"
   "sm-tree-9.5.jar;.\\l"
   "ibraries\\org\\ow2\\"
   "asm\\asm-util\\9.5\\"
   "asm-util-9.5.jar;.\\"
   "libraries\\org\\ow2"
   "\\asm\\asm-analysis"
   "\\9.5\\asm-analysis-"
   "9.5.jar;.\\libraries"
   "\\net\\minecraftforg"
   "e\\accesstransformer"
   "s\\8.0.4\\accesstran"
   "sformers-8.0.4.jar;."
   "\\libraries\\org\\an"
   "tlr\\antlr4-runtime"
   "\\4.9.1\\antlr4-runt"
   "ime-4.9.1.jar;.\\lib"
   "raries\\net\\minecra"
   "ftforge\\eventbus\\6"
   ".0.5\\eventbus-6.0.5"
   ".jar;.\\libraries\\n"
   "et\\minecraftforge\\"
   "forgespi\\7.0.1\\for"
   "gespi-7.0.1.jar;.\\l"
   "ibraries\\net\\minec"
   "raftforge\\coremods"
   "\\5.0.1\\coremods-5."
   "0.1.jar;.\\libraries"
   "\\cpw\\mods\\modlaun"
   "cher\\10.0.9\\modlau"
   "ncher-10.0.9.jar;.\\"
   "libraries\\net\\mine"
   "craftforge\\unsafe\\"
   "0.2.0\\unsafe-0.2.0."
   "jar;.\\libraries\\ne"
   "t\\minecraftforge\\m"
   "ergetool\\1.1.5\\mer"
   "getool-1.1.5-api.jar"
   ";.\\libraries\\com\\"
   "electronwill\\night-"
   "config\\core\\3.6.4"
   "\\core-3.6.4.jar;.\\"
   "libraries\\com\\elec"
   "tronwill\\night-conf"
   "ig\\toml\\3.6.4\\tom"
   "l-3.6.4.jar;.\\libra"
   "ries\\org\\apache\\m"
   "aven\\maven-artifact"
   "\\3.8.5\\maven-artif"
   "act-3.8.5.jar;.\\lib"
   "raries\\net\\jodah\\"
   "typetools\\0.6.3\\ty"
   "petools-0.6.3.jar;."
   "\\libraries\\net\\mi"
   "necrell\\terminalcon"
   "soleappender\\1.2.0"
   "\\terminalconsoleapp"
   "ender-1.2.0.jar;.\\l"
   "ibraries\\org\\jline"
   "\\jline-reader\\3.12"
   ".1\\jline-reader-3.1"
   "2.1.jar;.\\libraries"
   "\\org\\jline\\jline-"
   "terminal\\3.12.1\\jl"
   "ine-terminal-3.12.1."
   "jar;.\\libraries\\or"
   "g\\spongepowered\\mi"
   "xin\\0.8.5\\mixin-0."
   "8.5.jar;.\\libraries"
   "\\org\\openjdk\\nash"
   "orn\\nashorn-core\\1"
   "5.3\\nashorn-core-15"
   ".3.jar;.\\libraries"
   "\\net\\minecraftforg"
   "e\\JarJarSelector\\0"
   ".3.19\\JarJarSelecto"
   "r-0.3.19.jar;.\\libr"
   "aries\\net\\minecraf"
   "tforge\\JarJarMetada"
   "ta\\0.3.19\\JarJarMe"
   "tadata-0.3.19.jar;."
   "\\libraries\\cpw\\mo"
   "ds\\bootstraplaunche"
   "r\\1.1.2\\bootstrapl"
   "auncher-1.1.2.jar;."
   "\\libraries\\net\\mi"
   "necraftforge\\JarJar"
   "FileSystems\\0.3.19"
   "\\JarJarFileSystems-"
   "0.3.19.jar;.\\librar"
   "ies\\net\\minecraftf"
   "orge\\fmlloader\\1.2"
   "0.1-47.1.0\\fmlloade"
   "r-1.20.1-47.1.0.jar;"
   ".\\libraries\\net\\m"
   "inecraftforge\\fmlea"
   "rlydisplay\\1.20.1-4"
   "7.1.0\\fmlearlydispl"
   "ay-1.20.1-47.1.0.jar"
   ";.\\libraries\\com\\"
   "github\\oshi\\oshi-c"
   "ore\\6.2.2\\oshi-cor"
   "e-6.2.2.jar;.\\libra"
   "ries\\com\\google\\c"
   "ode\\gson\\gson\\2.1"
   "0\\gson-2.10.jar;.\\"
   "libraries\\com\\goog"
   "le\\guava\\failureac"
   "cess\\1.0.1\\failure"
   "access-1.0.1.jar;.\\"
   "libraries\\com\\goog"
   "le\\guava\\guava\\31"
   ".1-jre\\guava-31.1-j"
   "re.jar;.\\libraries"
   "\\com\\ibm\\icu\\icu"
   "4j\\71.1\\icu4j-71.1"
   ".jar;.\\libraries\\c"
   "om\\mojang\\authlib"
   "\\4.0.43\\authlib-4."
   "0.43.jar;.\\librarie"
   "s\\com\\mojang\\bloc"
   "klist\\1.0.10\\block"
   "list-1.0.10.jar;.\\l"
   "ibraries\\com\\mojan"
   "g\\brigadier\\1.1.8"
   "\\brigadier-1.1.8.ja"
   "r;.\\libraries\\com"
   "\\mojang\\datafixeru"
   "pper\\6.0.8\\datafix"
   "erupper-6.0.8.jar;."
   "\\libraries\\com\\mo"
   "jang\\logging\\1.1.1"
   "\\logging-1.1.1.jar;"
   ".\\libraries\\com\\m"
   "ojang\\patchy\\2.2.1"
   "0\\patchy-2.2.10.jar"
   ";.\\libraries\\com\\"
   "mojang\\text2speech"
   "\\1.17.9\\text2speec"
   "h-1.17.9.jar;.\\libr"
   "aries\\commons-codec"
   "\\commons-codec\\1.1"
   "5\\commons-codec-1.1"
   "5.jar;.\\libraries\\"
   "commons-io\\commons-"
   "io\\2.11.0\\commons-"
   "io-2.11.0.jar;.\\lib"
   "raries\\commons-logg"
   "ing\\commons-logging"
   "\\1.2\\commons-loggi"
   "ng-1.2.jar;.\\librar"
   "ies\\io\\netty\\nett"
   "y-buffer\\4.1.82.Fin"
   "al\\netty-buffer-4.1"
   ".82.Final.jar;.\\lib"
   "raries\\io\\netty\\n"
   "etty-codec\\4.1.82.F"
   "inal\\netty-codec-4."
   "1.82.Final.jar;.\\li"
   "braries\\io\\netty\\"
   "netty-common\\4.1.82"
   ".Final\\netty-common"
   "-4.1.82.Final.jar;."
   "\\libraries\\io\\net"
   "ty\\netty-handler\\4"
   ".1.82.Final\\netty-h"
   "andler-4.1.82.Final."
   "jar;.\\libraries\\io"
   "\\netty\\netty-resol"
   "ver\\4.1.82.Final\\n"
   "etty-resolver-4.1.82"
   ".Final.jar;.\\librar"
   "ies\\io\\netty\\nett"
   "y-transport-classes-"
   "epoll\\4.1.82.Final"
   "\\netty-transport-cl"
   "asses-epoll-4.1.82.F"
   "inal.jar;.\\librarie"
   "s\\io\\netty\\netty-"
   "transport-native-uni"
   "x-common\\4.1.82.Fin"
   "al\\netty-transport-"
   "native-unix-common-4"
   ".1.82.Final.jar;.\\l"
   "ibraries\\io\\netty"
   "\\netty-transport\\4"
   ".1.82.Final\\netty-t"
   "ransport-4.1.82.Fina"
   "l.jar;.\\libraries\\"
   "it\\unimi\\dsi\\fast"
   "util\\8.5.9\\fastuti"
   "l-8.5.9.jar;.\\libra"
   "ries\\net\\java\\dev"
   "\\jna\\jna-platform"
   "\\5.12.1\\jna-platfo"
   "rm-5.12.1.jar;.\\lib"
   "raries\\net\\java\\d"
   "ev\\jna\\jna\\5.12.1"
   "\\jna-5.12.1.jar;.\\"
   "libraries\\net\\sf\\"
   "jopt-simple\\jopt-si"
   "mple\\5.0.4\\jopt-si"
   "mple-5.0.4.jar;.\\li"
   "braries\\org\\apache"
   "\\commons\\commons-c"
   "ompress\\1.21\\commo"
   "ns-compress-1.21.jar"
   ";.\\libraries\\org\\"
   "apache\\commons\\com"
   "mons-lang3\\3.12.0\\"
   "commons-lang3-3.12.0"
   ".jar;.\\libraries\\o"
   "rg\\apache\\httpcomp"
   "onents\\httpclient\\"
   "4.5.13\\httpclient-4"
   ".5.13.jar;.\\librari"
   "es\\org\\apache\\htt"
   "pcomponents\\httpcor"
   "e\\4.4.15\\httpcore-"
   "4.4.15.jar;.\\librar"
   "ies\\org\\apache\\lo"
   "gging\\log4j\\log4j-"
   "api\\2.19.0\\log4j-a"
   "pi-2.19.0.jar;.\\lib"
   "raries\\org\\apache"
   "\\logging\\log4j\\lo"
   "g4j-core\\2.19.0\\lo"
   "g4j-core-2.19.0.jar;"
   ".\\libraries\\org\\a"
   "pache\\logging\\log4"
   "j\\log4j-slf4j2-impl"
   "\\2.19.0\\log4j-slf4"
   "j2-impl-2.19.0.jar;."
   "\\libraries\\org\\jo"
   "ml\\joml\\1.10.5\\jo"
   "ml-1.10.5.jar;.\\lib"
   "raries\\org\\lwjgl\\"
   "lwjgl-glfw\\3.3.1\\l"
   "wjgl-glfw-3.3.1.jar;"
   ".\\libraries\\org\\l"
   "wjgl\\lwjgl-glfw\\3."
   "3.1\\lwjgl-glfw-3.3."
   "1-natives-windows.ja"
   "r;.\\libraries\\org"
   "\\lwjgl\\lwjgl-glfw"
   "\\3.3.1\\lwjgl-glfw-"
   "3.3.1-natives-window"
   "s-arm64.jar;.\\libra"
   "ries\\org\\lwjgl\\lw"
   "jgl-glfw\\3.3.1\\lwj"
   "gl-glfw-3.3.1-native"
   "s-windows-x86.jar;."
   "\\libraries\\org\\lw"
   "jgl\\lwjgl-jemalloc"
   "\\3.3.1\\lwjgl-jemal"
   "loc-3.3.1.jar;.\\lib"
   "raries\\org\\lwjgl\\"
   "lwjgl-jemalloc\\3.3."
   "1\\lwjgl-jemalloc-3."
   "3.1-natives-windows."
   "jar;.\\libraries\\or"
   "g\\lwjgl\\lwjgl-jema"
   "lloc\\3.3.1\\lwjgl-j"
   "emalloc-3.3.1-native"
   "s-windows-arm64.jar;"
   ".\\libraries\\org\\l"
   "wjgl\\lwjgl-jemalloc"
   "\\3.3.1\\lwjgl-jemal"
   "loc-3.3.1-natives-wi"
   "ndows-x86.jar;.\\lib"
   "raries\\org\\lwjgl\\"
   "lwjgl-openal\\3.3.1"
   "\\lwjgl-openal-3.3.1"
   ".jar;.\\libraries\\o"
   "rg\\lwjgl\\lwjgl-ope"
   "nal\\3.3.1\\lwjgl-op"
   "enal-3.3.1-natives-w"
   "indows.jar;.\\librar"
   "ies\\org\\lwjgl\\lwj"
   "gl-openal\\3.3.1\\lw"
   "jgl-openal-3.3.1-nat"
   "ives-windows-arm64.j"
   "ar;.\\libraries\\org"
   "\\lwjgl\\lwjgl-opena"
   "l\\3.3.1\\lwjgl-open"
   "al-3.3.1-natives-win"
   "dows-x86.jar;.\\libr"
   "aries\\org\\lwjgl\\l"
   "wjgl-opengl\\3.3.1\\"
   "lwjgl-opengl-3.3.1.j"
   "ar;.\\libraries\\org"
   "\\lwjgl\\lwjgl-openg"
   "l\\3.3.1\\lwjgl-open"
   "gl-3.3.1-natives-win"
   "dows.jar;.\\librarie"
   "s\\org\\lwjgl\\lwjgl"
   "-opengl\\3.3.1\\lwjg"
   "l-opengl-3.3.1-nativ"
   "es-windows-arm64.jar"
   ";.\\libraries\\org\\"
   "lwjgl\\lwjgl-opengl"
   "\\3.3.1\\lwjgl-openg"
   "l-3.3.1-natives-wind"
   "ows-x86.jar;.\\libra"
   "ries\\org\\lwjgl\\lw"
   "jgl-stb\\3.3.1\\lwjg"
   "l-stb-3.3.1.jar;.\\l"
   "ibraries\\org\\lwjgl"
   "\\lwjgl-stb\\3.3.1\\"
   "lwjgl-stb-3.3.1-nati"
   "ves-windows.jar;.\\l"
   "ibraries\\org\\lwjgl"
   "\\lwjgl-stb\\3.3.1\\"
   "lwjgl-stb-3.3.1-nati"
   "ves-windows-arm64.ja"
   "r;.\\libraries\\org"
   "\\lwjgl\\lwjgl-stb\\"
   "3.3.1\\lwjgl-stb-3.3"
   ".1-natives-windows-x"
   "86.jar;.\\libraries"
   "\\org\\lwjgl\\lwjgl-"
   "tinyfd\\3.3.1\\lwjgl"
   "-tinyfd-3.3.1.jar;."
   "\\libraries\\org\\lw"
   "jgl\\lwjgl-tinyfd\\3"
   ".3.1\\lwjgl-tinyfd-3"
   ".3.1-natives-windows"
   ".jar;.\\libraries\\o"
   "rg\\lwjgl\\lwjgl-tin"
   "yfd\\3.3.1\\lwjgl-ti"
   "nyfd-3.3.1-natives-w"
   "indows-arm64.jar;.\\"
   "libraries\\org\\lwjg"
   "l\\lwjgl-tinyfd\\3.3"
   ".1\\lwjgl-tinyfd-3.3"
   ".1-natives-windows-x"
   "86.jar;.\\libraries"
   "\\org\\lwjgl\\lwjgl"
   "\\3.3.1\\lwjgl-3.3.1"
   ".jar;.\\libraries\\o"
   "rg\\lwjgl\\lwjgl\\3."
   "3.1\\lwjgl-3.3.1-nat"
   "ives-windows.jar;.\\"
   "libraries\\org\\lwjg"
   "l\\lwjgl\\3.3.1\\lwj"
   "gl-3.3.1-natives-win"
   "dows-arm64.jar;.\\li"
   "braries\\org\\lwjgl"
   "\\lwjgl\\3.3.1\\lwjg"
   "l-3.3.1-natives-wind"
   "ows-x86.jar;.\\libra"
   "ries\\org\\slf4j\\sl"
   "f4j-api\\2.0.1\\slf4"
   "j-api-2.0.1.jar;.\\v"
   "ersions\\forge-1.20."
   "1-47.1.0\\forge-1.20"
   ".1-47.1.0.jar -Djava"
   ".net.preferIPv6Addre"
   "sses=system -Dignore"
   "List=bootstraplaunch"
   "er,securejarhandler,"
   "asm-commons,asm-util"
   ",asm-analysis,asm-tr"
   "ee,asm,JarJarFileSys"
   "tems,client-extra,fm"
   "lcore,javafmllanguag"
   "e,lowcodelanguage,mc"
   "language,forge-,forg"
   "e-1.20.1-47.1.0.jar "
   "-DmergeModules=jna-5"
   ".10.0.jar,jna-platfo"
   "rm-5.10.0.jar -Dlibr"
   "aryDirectory=.\\libr"
   "aries -p .\\librarie"
   "s/cpw/mods/bootstrap"
   "launcher/1.1.2/boots"
   "traplauncher-1.1.2.j"
   "ar;.\\libraries/cpw/"
   "mods/securejarhandle"
   "r/2.1.10/securejarha"
   "ndler-2.1.10.jar;.\\"
   "libraries/org/ow2/as"
   "m/asm-commons/9.5/as"
   "m-commons-9.5.jar;."
   "\\libraries/org/ow2/"
   "asm/asm-util/9.5/asm"
   "-util-9.5.jar;.\\lib"
   "raries/org/ow2/asm/a"
   "sm-analysis/9.5/asm-"
   "analysis-9.5.jar;.\\"
   "libraries/org/ow2/as"
   "m/asm-tree/9.5/asm-t"
   "ree-9.5.jar;.\\libra"
   "ries/org/ow2/asm/asm"
   "/9.5/asm-9.5.jar;.\\"
   "libraries/net/minecr"
   "aftforge/JarJarFileS"
   "ystems/0.3.19/JarJar"
   "FileSystems-0.3.19.j"
   "ar --add-modules ALL"
   "-MODULE-PATH --add-o"
   "pens java.base/java."
   "util.jar=cpw.mods.se"
   "curejarhandler --add"
   "-opens java.base/jav"
   "a.lang.invoke=cpw.mo"
   "ds.securejarhandler "
   "--add-exports java.b"
   "ase/sun.security.uti"
   "l=cpw.mods.securejar"
   "handler --add-export"
   "s jdk.naming.dns/com"
   ".sun.jndi.dns=java.n"
   "aming cpw.mods.boots"
   "traplauncher.Bootstr"
   "apLauncher --usernam"
   "e mikitest --version"
   " forge-1.20.1-47.1.0"
   " --gameDir . --asset"
   "sDir .\\assets --ass"
   "etIndex 5 --uuid - -"
   "-accessToken - --cli"
   "entId ${clientid} --"
   "xuid ${auth_xuid} --"
   "userType msa --versi"
   "onType release --lau"
   "nchTarget forgeclien"
   "t --fml.forgeVersion"
   " 47.1.0 --fml.mcVers"
   "ion 1.20.1 --fml.for"
   "geGroup net.minecraf"
   "tforge --fml.mcpVers"
   "ion 20230612.114412");

subprocess.Popen(minecraft_command)

#print(" ".join(minecraft_command))
time.sleep(3)